-- DoLado — Recria o esquema interno "supabase_functions" que os Database
-- Webhooks do Supabase esperam encontrar. Nunca chegou a ser criado neste
-- projecto (falha de bootstrap), o que impedia criar qualquer webhook
-- ("ERROR: 3F000: schema supabase_functions does not exist"). Este SQL é
-- exactamente o que o Supabase cria por omissão — não contém nenhum segredo.

create schema if not exists supabase_functions;

create table if not exists supabase_functions.migrations (
    version text primary key,
    inserted_at timestamptz not null default now()
);

create table if not exists supabase_functions.hooks (
  id bigint generated by default as identity primary key,
  hook_table_id integer not null,
  hook_name text not null,
  created_at timestamptz not null default now(),
  request_id bigint
);

create index if not exists supabase_functions_hooks_h_table_id_h_name_idx
  on supabase_functions.hooks (hook_table_id, hook_name);

create or replace function supabase_functions.http_request()
returns trigger
language plpgsql
as $function$
  declare
    request_id bigint;
    payload jsonb;
    url text := TG_ARGV[0]::text;
    method text := TG_ARGV[1]::text;
    headers jsonb default '{}'::jsonb;
    params jsonb default '{}'::jsonb;
    timeout_ms integer default 1000;
  begin
    if url is null or url = 'null' then
      raise exception 'url argument is missing';
    end if;

    if method is null or method = 'null' then
      raise exception 'method argument is missing';
    end if;

    if TG_ARGV[2] is null or TG_ARGV[2] = 'null' then
      headers = '{"Content-Type": "application/json"}'::jsonb;
    else
      headers = TG_ARGV[2]::jsonb;
    end if;

    if TG_ARGV[3] is null or TG_ARGV[3] = 'null' then
      params = '{}'::jsonb;
    else
      params = TG_ARGV[3]::jsonb;
    end if;

    if TG_ARGV[4] is null or TG_ARGV[4] = 'null' then
      timeout_ms = 1000;
    else
      timeout_ms = TG_ARGV[4]::integer;
    end if;

    case
      when method = 'GET' then
        select http_get into request_id from net.http_get(
          url,
          params,
          headers,
          timeout_ms
        );
      when method = 'POST' then
        payload = jsonb_build_object(
          'old_record', OLD,
          'record', NEW,
          'type', TG_OP,
          'table', TG_TABLE_NAME,
          'schema', TG_TABLE_SCHEMA
        );

        select http_post into request_id from net.http_post(
          url,
          payload,
          params,
          headers,
          timeout_ms
        );
      else
        raise exception 'method argument % is invalid', method;
    end case;

    insert into supabase_functions.hooks
      (hook_table_id, hook_name, request_id)
    values
      (TG_RELID, TG_NAME, request_id);

    return NEW;
  end
$function$;
