-- DoLado — Carga jurídica 4: Gás, Compras & Reembolsos, Ginásios (06/10/2026)
--
-- Relatório de validação e fontes: docs/legal/rascunho-carga-juridica-4-novos-setores.md
-- Textos oficiais lidos a 06/10/2026 (DRE e ERSE, versões consolidadas):
--   RRC — Regulamento n.º 827/2023 (1.ª alteração: Regulamento n.º 8/2026, só art. 131.º, n.º 4);
--   RQS — Regulamento n.º 826/2023 (alterações: Diretiva n.º 21/2024 e Regulamento n.º 8/2026,
--         sem efeito nos artigos usados);
--   DL 101/2011; DL 84/2021 (sem alterações); DL 24/2014 (última: Lei 10/2023);
--   Lei 24/96 (última: Lei 28/2023); DL 446/85 (última: DL 123/2023); Lei 39/2012 (última: DL 9/2021).
--
-- Regras:
--   * TODAS entram com ativa = false, revista_em = null, revista_por = null —
--     a IA não as recebe enquanto Thiago/advogada não as reverem e ativarem.
--   * Não altera nenhuma das 108 regras das cargas 1–3 (códigos novos).
--   * ON CONFLICT só atualiza regras desta carga que ainda não foram revistas
--     nem ativadas: uma regra revista nunca é reescrita por esta migration.
--   * A IA recebe título, diploma, artigo, resumo e condições (paraEnvio,
--     src/lib/rascunhoIA/regras.ts). Por isso, nas regras de apoio à análise
--     humana, a cautela ("necessita de análise concreta") está no resumo e nas
--     condições, e não só em efeito_juridico.

insert into public.regras_juridicas (
  codigo, setor, categoria, subcategoria, titulo, diploma, artigo, resumo,
  condicoes_aplicabilidade, fonte_url, em_vigor_desde, revogada_em, ativa, revista_em, revista_por,
  efeito_juridico, provas_necessarias, resultado_pretendido, palavras_chave
) values

-- ===========================================================================
-- GÁS (setor 'Gás') — 21 regras
-- ===========================================================================

('GAS_FIDELIZACAO_CONTRAPARTIDA_19', 'Gás', 'Fidelização', 'Gás natural — fidelização',
 'Fidelização exige contrapartida e destaque na proposta',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 19.º, n.os 1 a 3',
 'Num contrato de fornecimento de gás, a estipulação de um período de fidelização depende da existência de uma contrapartida para o cliente associada a essa vinculação. A proposta contratual deve incluir uma referência expressa, separada e destacada à eventual existência do período de fidelização, à indemnização aplicável em caso de não cumprimento e à duração ou à data de cessação desse período. O incumprimento deste dever é invocável pelo cliente e determina a exclusão da cláusula de fidelização do contrato. Saber se existiu contrapartida e se a referência foi suficientemente destacada necessita de análise concreta.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Deve existir cláusula de fidelização e estar disponível a proposta contratual (ou ficha/gravação); identificar a contrapartida concreta e a forma como a fidelização, a indemnização e a duração foram apresentadas.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Se a proposta não referiu de forma expressa, separada e destacada a fidelização, a indemnização e a duração, o cliente pode invocar a exclusão da cláusula de fidelização. A existência de contrapartida e a suficiência do destaque exigem análise humana.',
 'Proposta contratual; ficha contratual; contrato e condições particulares; gravação da contratação, se existir; faturas que indiquem a fidelização.',
 'Exclusão da cláusula de fidelização e afastamento da indemnização nela baseada, quando os requisitos regulamentares não foram cumpridos.',
 array['fidelização', 'contrapartida', 'gás', 'penalização', 'proposta contratual', 'destaque']),

('GAS_FIDELIZACAO_MAX_12M_19', 'Gás', 'Fidelização', 'Gás natural — fidelização',
 'Fidelização de consumidores limitada a 12 meses',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 19.º, n.º 4',
 'O período de fidelização acordado com consumidores num contrato de fornecimento de gás não pode ter uma duração superior a 12 meses.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Cliente consumidor; duração ou datas de início e fim da fidelização conhecidas.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Uma fidelização acordada com consumidor por mais de 12 meses contraria o limite regulamentar; pode contestar-se a aplicação de encargos baseados no período que excede esse limite.',
 'Contrato; proposta comercial; ficha contratual; datas de início e de fim da fidelização.',
 'Correção do período de fidelização e afastamento de encargos baseados numa duração superior a 12 meses.',
 array['fidelização', '12 meses', 'gás', 'duração', 'penalização']),

('GAS_FIDELIZACAO_CONDICOES_19', 'Gás', 'Alteração contratual', 'Gás natural — fidelização',
 'Condições e preço não podem mudar durante a fidelização',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 19.º, n.os 5 e 7; artigo 68.º, n.º 4',
 'Enquanto estiver em vigor um período de fidelização, o comercializador não pode alterar as condições contratuais, incluindo as relativas ao preço, exceto se for do interesse do cliente e houver acordo expresso. Nos contratos celebrados com consumidores, a definição de um período de fidelização obsta à estipulação de indexação das condições de preço ou de ofertas a preços dinâmicos. Saber se uma alteração é do interesse do cliente necessita de análise concreta.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Período de fidelização em vigor à data da alteração; identificar a alteração e se houve acordo expresso do cliente.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Uma alteração de condições, incluindo de preço, durante a fidelização e sem acordo expresso do cliente pode ser contestada. O interesse do cliente na alteração exige análise humana.',
 'Contrato; ficha contratual; comunicação da alteração; faturas antes e depois; prova de eventual acordo do cliente.',
 'Reposição das condições contratadas e correção das faturas emitidas com as condições alteradas.',
 array['aumento de preço', 'fidelização', 'alteração de condições', 'gás', 'indexação', 'preço dinâmico']),

('GAS_FIDELIZACAO_RENOVACAO_19', 'Gás', 'Fidelização', 'Gás natural — fidelização',
 'Nova fidelização não se renova automaticamente',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 19.º, n.º 6',
 'A estipulação de um novo período de fidelização pressupõe o cumprimento dos deveres de informação previstos no artigo 19.º e não é suscetível de renovação automática.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Terminou um período de fidelização e o comercializador considera iniciado outro; verificar se houve nova manifestação de vontade com a informação exigida.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Um novo período de fidelização não pode resultar apenas da renovação automática do contrato.',
 'Contrato inicial; data de fim da fidelização anterior; comunicações de renovação; eventual nova aceitação.',
 'Afastamento da nova fidelização imposta por renovação automática e dos encargos nela baseados.',
 array['renovação automática', 'nova fidelização', 'gás', 'fidelização renovada']),

('GAS_FIDELIZACAO_INDEMNIZACAO_19', 'Gás', 'Fidelização', 'Gás natural — fidelização',
 'Indemnização pela fidelização tem de ser proporcionada',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 19.º, n.os 9 a 11',
 'O incumprimento da cláusula de fidelização pelo cliente obriga-o a indemnizar a outra parte, nos termos estipulados contratualmente. Essa indemnização deve ser proporcionada e não pode exceder as perdas económicas diretas para o comercializador resultantes da cessação do contrato, incluindo os custos de quaisquer investimentos ou serviços agrupados que já tenham sido prestados no âmbito do contrato. A fatura deve incluir a informação relativa à data do termo do período de fidelização. A proporcionalidade do valor concreto necessita de análise concreta.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Fidelização válida em vigor; cessação antecipada pelo cliente; valor exigido e respetiva justificação conhecidos.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Permite pedir a justificação do valor e contestar uma indemnização que exceda as perdas económicas diretas resultantes da cessação; a fatura sem a data do termo da fidelização não cumpre o n.º 11. A proporcionalidade exige análise humana.',
 'Contrato; cálculo da indemnização exigida; fatura final; faturas anteriores (data do termo da fidelização).',
 'Redução da indemnização ao limite regulamentar e indicação da data do termo da fidelização nas faturas.',
 array['indemnização', 'penalização', 'fidelização', 'cancelamento antecipado', 'gás', 'perdas diretas']),

('GAS_DENUNCIA_SEM_ENCARGOS_81', 'Gás', 'Cancelamento', 'Gás natural — cessação do contrato',
 'Cliente pode denunciar a todo o tempo sem encargos, salvo fidelização',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 81.º, n.º 1, alínea b), e n.os 2 a 4',
 'A cessação do contrato de fornecimento pode verificar-se por denúncia ou oposição à renovação por parte do cliente, a todo o tempo, sem encargos, salvo se estiver vigente um período de fidelização. O comercializador não pode denunciar o contrato durante a sua vigência, sem prejuízo do artigo 19.º. Nos contratos com consumidores, o comercializador não pode opor-se à renovação, salvo se tiverem ocorrido pelo menos três incumprimentos de pagamento tempestivo nos doze meses imediatamente anteriores ou se pretender cessar a atividade de comercialização ou não celebrar de forma generalizada novos contratos; quando permitida, a oposição depende de pré-aviso mínimo de 45 dias, com indicação expressa de que, na ausência de nova contratação, haverá interrupção do fornecimento.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Verificar se existe período de fidelização em vigor, quem pôs termo ao contrato, as datas e o pré-aviso.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Fora de um período de fidelização, a denúncia ou oposição à renovação pelo cliente não pode gerar encargos. A oposição à renovação pelo comercializador fora destes casos ou sem o pré-aviso pode ser contestada.',
 'Contrato; pedido de denúncia e respetiva data; comunicação do comercializador; faturas com encargos de cessação.',
 'Eliminação de encargos de cessação indevidos ou manutenção do contrato quando a oposição do comercializador não é admitida.',
 array['cancelar contrato', 'denúncia', 'sem encargos', 'gás', 'oposição à renovação', 'rescisão']),

('GAS_ALT_CONTRATO_68', 'Gás', 'Alteração contratual', 'Gás natural — alteração de condições',
 'Alteração das condições exige aviso de 30 dias',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 68.º, n.os 1 a 3 e 5',
 'No final de cada período contratual o comercializador pode propor a alteração das condições para o período seguinte; no decurso de um período contratual, com consumidores, as alterações só podem ser propostas de forma fundamentada e quando essa possibilidade esteja prevista no contrato. As novas condições devem ser enviadas com antecedência mínima de 30 dias relativamente à data em que passem a aplicar-se, com indicação expressa do direito do cliente à denúncia do contrato ou à oposição à renovação, em ambos os casos sem encargos, caso não as aceite. Existindo previsão contratual expressa, nas variações de preço que decorram da mera alteração das tarifas de acesso às redes ou das tarifas de venda do comercializador de último recurso aprovadas pela ERSE, estes deveres consideram-se cumpridos com a explicitação da alteração e da sua repercussão no preço final na primeira fatura que a aplique.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Alteração por iniciativa do comercializador; data da comunicação e data de aplicação; verificar se se trata da exceção do n.º 5. Durante a fidelização aplica-se também o artigo 19.º.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Uma alteração aplicada sem os 30 dias de antecedência ou sem a indicação do direito de sair sem encargos pode ser contestada; o cliente que não aceita as novas condições pode denunciar o contrato ou opor-se à renovação sem encargos.',
 'Comunicação da alteração; contrato; faturas antes e depois; data de receção da comunicação.',
 'Reposição das condições anteriores até ao cumprimento do procedimento, ou saída do contrato sem encargos.',
 array['alteração de condições', 'aumento de preço', '30 dias', 'gás', 'denúncia sem encargos']),

('GAS_ACEITACAO_EXPRESSA_20', 'Gás', 'Contrato', 'Gás natural — contratação',
 'Contrato exige aceitação expressa registada em suporte duradouro',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 20.º',
 'A aceitação da proposta de fornecimento apresentada pelo comercializador depende de declaração expressa, registada em suporte duradouro, do cliente, enquanto titular do contrato de fornecimento. Esse registo deve ser conservado pelo prazo de três anos ou pelo tempo de duração do contrato acrescido do prazo de caducidade ou prescrição, quando este tenha duração superior.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. O cliente contesta ter celebrado ou alterado o contrato (por exemplo, mudança de comercializador não autorizada).',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Sem registo em suporte duradouro da declaração expressa do titular, o comercializador não demonstra a aceitação, havendo fundamento para contestar a contratação ou alteração invocada.',
 'Pedido do registo da aceitação; contrato; gravação da chamada; confirmações recebidas; comunicações.',
 'Obtenção da prova da aceitação ou, na sua falta, reversão da contratação ou alteração.',
 array['não contratei', 'aceitação', 'contrato não autorizado', 'gás', 'suporte duradouro']),

('GAS_CAUCAO_23_27', 'Gás', 'Cobrança', 'Gás natural — caução',
 'Caução a consumidores só em situações limitadas e restituição',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 23.º, n.os 1, 2, 5 e 6; artigo 27.º',
 'Se o cliente for consumidor, o comercializador só tem o direito de exigir a prestação de caução nas situações de restabelecimento do fornecimento na sequência de interrupção decorrente de incumprimento contratual imputável ao cliente (nas instalações eventuais ou provisórias pode sempre exigi-la). O consumidor pode, em qualquer momento, obstar à prestação de caução se, estando regularizada a dívida, optar pela transferência bancária como meio de pagamento. A caução prestada por consumidor deve ser restituída, sem necessidade de pedido, na cessação do contrato, atualizada com base no índice de preços no consumidor e depois de deduzidos os montantes em dívida; deve também ser restituída se o cliente passar a pagar por transferência bancária ou permanecer em cumprimento contratual, continuadamente, durante dois anos.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Cliente consumidor; motivo da exigência da caução; existência de interrupção e restabelecimento; data de cessação ou histórico de pagamentos.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Caução exigida a consumidor fora da situação prevista pode ser contestada; a falta de restituição nos casos indicados também.',
 'Pedido de caução; comprovativo do valor; histórico de interrupções e pagamentos; documento de cessação; fatura final.',
 'Anulação da caução indevida ou restituição da caução atualizada.',
 array['caução', 'depósito', 'restituição', 'gás', 'restabelecimento', 'transferência bancária']),

('GAS_LEITURA_ESTIMATIVA_42', 'Gás', 'Faturação', 'Gás natural — leituras e estimativas',
 'Leitura real prevalece; regras próprias das estimativas no gás',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 42.º, n.os 3 a 7',
 'Nos contratos de fornecimento de gás deve prevalecer, sempre que existente, a mais recente informação de consumos obtida por leitura direta dos equipamentos de medição, incluindo a comunicada pelo cliente. Para efeitos de estimativa de consumos, o cliente tem o direito de escolher a metodologia entre as opções do Guia de Medição, Leitura e Disponibilização de Dados, cabendo ao comercializador registar e atualizar essa opção em suporte duradouro. As estimativas são expressas na unidade de medida do equipamento de medição, sem prejuízo de a faturação de gás ser feita em kWh, com indicação obrigatória dos fatores de conversão quando aplicável. No setor do gás, o comercializador só pode realizar estimativas para faturação quando se refiram a um período não abrangido pelos dados de consumo ou estimativas disponibilizados pelo operador da rede e utilizem a metodologia escolhida pelo cliente.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Fatura com consumos estimados ou acerto; leituras reais (incluindo autoleituras) e respetivas datas.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Pode fundamentar o recálculo de faturas baseadas em estimativa quando existia leitura real mais recente, quando a metodologia não é a escolhida pelo cliente ou quando faltam os fatores de conversão para kWh.',
 'Faturas; autoleituras e comprovativo do envio; fotografia do contador; histórico de leituras; metodologia de estimativa escolhida.',
 'Recálculo das faturas com a leitura real ou a metodologia escolhida e devolução ou crédito dos valores em excesso.',
 array['leitura real', 'estimativa', 'autoleitura', 'contador', 'gás', 'kWh', 'fator de conversão']),

('GAS_FATURACAO_PERIODICIDADE_44', 'Gás', 'Faturação', 'Gás natural — periodicidade',
 'Faturação mensal e fracionamento de faturas acumuladas',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 44.º',
 'Salvo acordo em contrário no interesse do cliente, os comercializadores devem emitir as faturas com periodicidade mensal. Sempre que a periodicidade acordada não for observada, o pagamento do valor exigido pode ser fracionado em prestações mensais, a pedido do cliente, considerando o período de faturação apresentado a pagamento, sem prejuízo do regime de prescrição e caducidade, devendo o comercializador informar previamente o cliente desse direito. Se o incumprimento da periodicidade resultar de facto não imputável ao cliente, às prestações não podem acrescer quaisquer juros legais ou convencionados.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Fatura que acumula um período superior ao acordado; causa do atraso.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Direito a pedir o fracionamento em prestações mensais e, se o atraso não for imputável ao cliente, sem juros.',
 'Fatura acumulada; histórico de faturas; contrato; datas dos períodos faturados.',
 'Plano de pagamento em prestações mensais, sem juros quando o atraso não é imputável ao cliente.',
 array['fatura acumulada', 'fatura atrasada', 'prestações', 'sem juros', 'gás', 'faturação mensal']),

('GAS_FATURA_PAPEL_45', 'Gás', 'Faturação', 'Gás natural — fatura',
 'Fatura em papel sem acréscimo de despesa',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 45.º, n.º 1',
 'A fatura relativa ao fornecimento de gás é enviada preferencialmente em suporte eletrónico, salvo se o cliente optar por recebê-la em papel, não podendo daí decorrer qualquer acréscimo de despesa para o cliente.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Existe cobrança associada à opção pela fatura em papel.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'O custo cobrado pela opção pela fatura em papel não é devido.',
 'Fatura com o encargo; contrato; preçário.',
 'Eliminação do encargo e devolução dos valores cobrados.',
 array['fatura em papel', 'taxa', 'custo fatura', 'gás']),

('GAS_CORTE_PREAVISO_79', 'Gás', 'Suspensão', 'Gás natural — interrupção',
 'Interrupção por facto imputável ao cliente: causas e pré-aviso',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 78.º, n.º 1; artigo 79.º, n.os 1 a 3, 6 e 12',
 'O fornecimento de gás só pode ser interrompido por facto imputável ao cliente nas situações do artigo 78.º, n.º 1, entre as quais a falta de pagamento no prazo estipulado ou a falta de prestação de caução, quando exigível, a pedido do comercializador, e a impossibilidade de acesso ao equipamento de medição. Salvo nos casos de cedência de gás a terceiros não autorizada e de incumprimento das disposições relativas à segurança de pessoas e bens, a interrupção só pode ocorrer após pré-aviso escrito, que deve indicar o motivo, os meios ao dispor do cliente para a evitar, as condições de restabelecimento, os preços dos serviços de interrupção e restabelecimento e o dia a partir do qual pode ocorrer. Nos casos das alíneas c), d), e), i), j) e l) do n.º 1 do artigo 78.º (incluindo falta de pagamento e de caução), a antecedência mínima é de 20 dias; tratando-se de clientes economicamente vulneráveis, de 30 dias.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Identificar a causa invocada, a data de envio ou receção do pré-aviso, o seu conteúdo e a data da interrupção; condição de cliente economicamente vulnerável, se aplicável.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Uma interrupção fora das causas previstas, sem pré-aviso, com antecedência inferior à regulamentar ou sem os elementos obrigatórios pode ser contestada.',
 'Pré-aviso; comprovativo da data de envio ou receção; faturas em dívida; data efetiva da interrupção; prova da condição de cliente economicamente vulnerável.',
 'Cancelamento da interrupção ou restabelecimento e contestação dos encargos de uma interrupção irregular.',
 array['corte', 'interrupção', 'pré-aviso', '20 dias', '30 dias', 'cliente vulnerável', 'gás', 'falta de pagamento']),

('GAS_CORTE_PRESCRICAO_78', 'Gás', 'Suspensão', 'Gás natural — interrupção',
 'Dívida prescrita ou caducada não permite interrupção',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 78.º, n.º 2',
 'A falta de pagamento dos montantes devidos não permite a interrupção do fornecimento de gás quando seja invocada a prescrição ou a caducidade, nos termos e pelos meios previstos na lei.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. A dívida invocada está abrangida por prescrição ou caducidade e estas foram invocadas.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Impede a interrupção do fornecimento com fundamento numa dívida cuja prescrição ou caducidade foi invocada nos termos legais.',
 'Faturas e períodos de consumo; comunicação de cobrança; invocação da prescrição ou caducidade; aviso de interrupção.',
 'Cancelamento da interrupção baseada nessa dívida.',
 array['prescrição', 'caducidade', 'corte', 'dívida antiga', 'gás']),

('GAS_CORTE_DIA_UTIL_79', 'Gás', 'Suspensão', 'Gás natural — interrupção',
 'Sem interrupção no último dia útil da semana nem na véspera de feriado',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 79.º, n.º 11',
 'No caso dos clientes com consumo anual de gás inferior ou igual a 10 000 m3 (n), a interrupção do fornecimento por facto imputável ao cliente não pode ter lugar no último dia útil da semana ou na véspera de um feriado, salvo nos casos de cedência de gás a terceiros não autorizada e de incumprimento das disposições legais e regulamentares relativas à segurança de pessoas e bens.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Consumo anual até 10 000 m3 (n); data da interrupção; causa da interrupção.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Uma interrupção nesses dias, fora das duas exceções, contraria o regulamento.',
 'Data e hora da interrupção; faturas com o consumo anual ou escalão; pré-aviso.',
 'Reconhecimento da irregularidade da interrupção e restabelecimento.',
 array['corte à sexta-feira', 'véspera de feriado', 'interrupção', 'gás', '10 000 m3']),

('GAS_RESTABELECIMENTO_RQS_90', 'Gás', 'Suspensão', 'Gás natural — restabelecimento',
 'Prazos de restabelecimento depois de sanada a situação',
 'Regulamento n.º 826/2023, de 28 de julho — RQS dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 88.º, n.os 3 e 4; artigo 89.º; artigo 90.º, n.º 1, alínea b), e n.os 2, 3 e 7',
 'As obrigações de restabelecimento aplicam-se quando a situação que deu origem à interrupção estiver sanada; quando sejam devidos pagamentos, considera-se sanada após boa cobrança. Sanada a situação com o comercializador, este deve comunicá-lo ao operador de rede de distribuição no prazo máximo de 30 minutos; o incumprimento confere ao comercializador o dever de compensação ao cliente. Se for necessária deslocação, o operador de rede de gás deve chegar à instalação no prazo máximo de 12 horas para consumidores, 8 horas para os restantes clientes, ou 4 horas se o cliente pedir expressamente o restabelecimento urgente e pagar o preço adicional; a contagem suspende-se das 0h00 às 8h00, exceto para clientes prioritários. Estes prazos só se aplicam quando o restabelecimento envolva ações simples. O incumprimento confere ao operador de rede o dever de compensação ao cliente.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RQS se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Situação sanada (data e hora da boa cobrança); data e hora do restabelecimento; tipo de cliente; pedido de restabelecimento urgente, se houve.',
 'https://www.erse.pt/media/sxlhtvlp/rqs_regulamento-da-qualidade-de-servi%C3%A7o_consolidado-2026.pdf', null, null, false, null, null,
 'O atraso no restabelecimento além destes prazos confere direito a compensação nos termos do RQS.',
 'Comprovativo e hora do pagamento; comunicações com o comercializador e o operador de rede; hora do restabelecimento.',
 'Restabelecimento e pagamento da compensação regulamentar.',
 array['restabelecimento', 'religação', 'gás', '12 horas', 'urgente', 'compensação']),

('GAS_RECLAMACAO_PRAZO_RQS_60', 'Gás', 'Reclamação', 'Gás natural — reclamações',
 'Prazo de resposta a reclamações e compensação',
 'Regulamento n.º 826/2023, de 28 de julho — RQS dos Setores Elétrico e do Gás, na redação vigente', 'Artigos 60.º e 61.º',
 'Os operadores de redes de distribuição devem responder às reclamações em 15 dias úteis; os comercializadores, no prazo definido contratualmente com o cliente, nunca superior a 15 dias úteis (15 dias úteis no caso de reclamantes não clientes). Na impossibilidade de cumprir por factos não imputáveis à entidade reclamada, esta deve informar o reclamante nesses prazos, por escrito, das diligências efetuadas, dos factos que impedem a resposta, do prazo expectável da resposta final e de um meio de contacto. As reclamações recebidas por escrito, ou em que o reclamante o peça, têm resposta escrita. O reclamante tem direito de compensação, por facto que não lhe seja imputável, quando não sejam cumpridos estes prazos, quando falte resposta depois do prazo indicado como expectável sem nova justificação ou quando a comunicação escrita não tenha o conteúdo mínimo.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RQS se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Data de receção da reclamação; entidade reclamada; prazo contratual; respostas recebidas.',
 'https://www.erse.pt/media/sxlhtvlp/rqs_regulamento-da-qualidade-de-servi%C3%A7o_consolidado-2026.pdf', null, null, false, null, null,
 'A falta de resposta no prazo, ou sem a comunicação exigida, confere direito a compensação nos termos do RQS.',
 'Reclamação e comprovativo de receção; contrato (prazo de resposta); respostas recebidas e respetivas datas.',
 'Resposta fundamentada e pagamento da compensação devida.',
 array['reclamação', '15 dias úteis', 'sem resposta', 'compensação', 'gás', 'comercializador']),

('GAS_RECLAM_FAT_CORTE_RQS_64', 'Gás', 'Reclamação', 'Gás natural — reclamações de faturação',
 'Reclamação de faturação fundamentada suspende ordem de corte',
 'Regulamento n.º 826/2023, de 28 de julho — RQS dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 64.º, n.os 1 a 4',
 'Nas reclamações relativas a faturação, o comercializador deve, no prazo de resposta aplicável, dar ao reclamante a informação necessária ao esclarecimento da situação (elementos para compreender os valores faturados, elementos da leitura do contador e resultado da apreciação) ou propor uma reunião ou contacto telefónico direto. A reclamação sobre faturação suspende eventuais ordens de interrupção por falta de pagamento da fatura reclamada até à apreciação da reclamação, desde que acompanhada de informações concretas e objetivas que evidenciem a possibilidade de erro de faturação, sem prejuízo do pagamento atempado de valores subsequentes não reclamados; a suspensão mantém-se se for pedida a intervenção da ERSE, até à resposta desta. Saber se a reclamação contém essas informações concretas e objetivas necessita de análise concreta.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RQS se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Reclamação sobre a faturação com elementos concretos de possível erro; ordem ou aviso de interrupção ligado à fatura reclamada.',
 'https://www.erse.pt/media/sxlhtvlp/rqs_regulamento-da-qualidade-de-servi%C3%A7o_consolidado-2026.pdf', null, null, false, null, null,
 'Suspende a interrupção relativa à fatura reclamada enquanto a reclamação é apreciada, nas condições regulamentares. A suficiência dos elementos da reclamação exige análise humana.',
 'Reclamação; fatura; leituras; aviso de corte; comprovativos de pagamento dos valores não reclamados.',
 'Suspensão do corte, esclarecimento da faturação e correção da fatura se se confirmar o erro.',
 array['fatura reclamada', 'corte', 'erro de faturação', 'gás', 'suspensão', 'ERSE']),

('GAS_RECLAM_CARACTERISTICAS_RQS_67', 'Gás', 'Qualidade de serviço', 'Gás natural — características e pressão',
 'Reclamações sobre as características do gás ou a pressão',
 'Regulamento n.º 826/2023, de 28 de julho — RQS dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 67.º; artigo 61.º, n.º 1, alínea d)',
 'A reclamação relativa às características do fornecimento de gás deve descrever factos que indiciem que estão fora das tolerâncias regulamentares. O operador de rede deve dar conhecimento por escrito das razões, das ações corretivas e do prazo de implementação, ou verificar a instalação, no prazo de 15 dias úteis após a apresentação da reclamação, ou após o pedido do comercializador quando a reclamação for apresentada a este (que deve fazer esse pedido até três dias úteis após a receber). Se a verificação comprovar que as características ou a pressão estão fora das tolerâncias, o operador de rede deve informar o período de fornecimento deficiente e as ações corretivas e preventivas; se não o confirmar, deve descrever as diligências efetuadas. O incumprimento dos n.os 3 e 4 do artigo 67.º confere direito a compensação.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RQS se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Problema de pressão ou de qualidade do gás; datas da reclamação, do pedido do comercializador e das respostas.',
 'https://www.erse.pt/media/sxlhtvlp/rqs_regulamento-da-qualidade-de-servi%C3%A7o_consolidado-2026.pdf', null, null, false, null, null,
 'Obriga o operador de rede a responder com estes conteúdos e prazos; o incumprimento dos n.os 3 e 4 confere direito a compensação.',
 'Reclamação com a descrição dos factos; respostas recebidas; relatórios de visita; datas.',
 'Verificação da instalação, correção do fornecimento e compensação quando devida.',
 array['pressão do gás', 'qualidade do gás', 'características', 'gás', 'operador de rede']),

('GAS_MUDANCA_COMERCIALIZADOR_242', 'Gás', 'Mudança de comercializador', 'Gás natural — mudança de comercializador',
 'Mudança gratuita em três semanas, dívidas e fatura final',
 'Regulamento n.º 827/2023, de 28 de julho — RRC dos Setores Elétrico e do Gás, na redação vigente', 'Artigo 242.º, n.os 3, 4, 11 a 13, 15 e 16',
 'A mudança de comercializador está isenta de encargos para os clientes e deve ocorrer num prazo máximo de três semanas a partir da data do pedido, salvo prazo legal ou regulamentar inferior ou data específica acordada entre o cliente e o novo comercializador. Na sequência da mudança, o cliente deve receber do comercializador cessante uma única fatura com o acerto final de contas, no prazo máximo de seis semanas após a efetivação da mudança. A existência de valores em dívida a um comercializador de gás não impede a mudança; constitui objeção admissível, na sua vigência, um plano de pagamento fracionado de valores em dívida ao comercializador (salvo cessão de créditos, assunção da dívida pelo novo comercializador ou antecipação do pagamento), e impede a escolha de outro comercializador a dívida vencida a um comercializador de último recurso que não tenha sido contestada em tribunal ou junto de entidade de resolução alternativa de litígios.',
 'Gás natural fornecido por rede. GPL canalizado: só depois de confirmado que o regime do RRC se aplica. Gás de garrafa: não aplicar. O formulário não distingue o tipo de gás — confirmar na revisão. Data do pedido e da efetivação da mudança; existência e natureza de dívida; data da fatura final.',
 'https://www.erse.pt/media/cw5fdm3i/regulamento-827-2023_consolidado.pdf', null, null, false, null, null,
 'Encargos pela mudança, atraso além de três semanas, bloqueio fora das objeções previstas ou fatura final fora do prazo podem ser contestados.',
 'Pedido de mudança; comunicações dos comercializadores; fatura final; plano de pagamentos, se existir.',
 'Concretização da mudança sem encargos e emissão da fatura final no prazo.',
 array['mudança de comercializador', 'trocar fornecedor', 'três semanas', 'fatura final', 'seis semanas', 'dívida', 'gás']),

('GAS_TARIFA_SOCIAL_DL101', 'Gás', 'Tarifa social', 'Gás natural — tarifa social',
 'Tarifa social do gás natural',
 'Decreto-Lei n.º 101/2011, de 30 de setembro, na redação vigente', 'Artigos 2.º, 5.º e 6.º',
 'Podem beneficiar da tarifa social de gás natural os clientes finais economicamente vulneráveis, entre os quais os beneficiários do complemento solidário para idosos, do rendimento social de inserção, de prestações de desemprego, do 1.º escalão do abono de família ou da pensão social de invalidez do regime especial de proteção na invalidez ou do complemento da prestação social para a inclusão, que reúnam cumulativamente: ser titulares de um contrato de fornecimento de gás natural; consumo destinado exclusivamente a uso doméstico em habitação permanente; instalação alimentada em baixa pressão; escalão de consumo anual inferior ou igual a 500 m3. Só num ponto de ligação por cliente. A Direção-Geral de Energia e Geologia identifica os beneficiários com a segurança social e a tarifa é atribuída automaticamente se o beneficiário não se opuser no prazo de 30 dias; o beneficiário pode também apresentar ao comercializador o comprovativo da sua condição.',
 'Só gás natural (não GPL nem gás de garrafa) — confirmar na revisão, porque o formulário não distingue o tipo de gás. Verificar todas as condições do artigo 5.º e a prestação social do artigo 2.º, n.º 2.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2011-149738212', null, null, false, null, null,
 'O cliente elegível tem direito à aplicação da tarifa social de gás natural e pode apresentar o comprovativo diretamente ao comercializador.',
 'Contrato; faturas (escalão e pressão); comprovativo da prestação social; comunicações da DGEG ou do comercializador.',
 'Aplicação da tarifa social e correção das faturas emitidas sem ela, quando confirmada a elegibilidade.',
 array['tarifa social', 'gás natural', '500 m3', 'cliente vulnerável', 'DGEG', 'desconto']),

-- ===========================================================================
-- COMPRAS & REEMBOLSOS (setor 'Compras & Reembolsos') — 15 regras
-- ===========================================================================

('COMPRA_CONFORMIDADE_5_7', 'Compras & Reembolsos', 'Conformidade', 'Falta de conformidade / garantia',
 'O profissional deve entregar bens conformes com o contrato',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigos 5.º a 7.º',
 'O profissional deve entregar ao consumidor bens conformes. São conformes os bens que correspondem à descrição, ao tipo, à quantidade e à qualidade e têm a funcionalidade e demais características previstas no contrato, são adequados à finalidade específica acordada e são entregues com os acessórios, instruções e atualizações estipulados. Devem ainda ser adequados ao uso a que se destinam bens da mesma natureza, corresponder à amostra ou modelo apresentado e ter a quantidade, as qualidades e as características (incluindo durabilidade, funcionalidade, compatibilidade e segurança) habituais e expectáveis em bens do mesmo tipo, considerando também declarações públicas do profissional ou do produtor, nomeadamente na publicidade ou rotulagem, salvo as exceções do artigo 7.º, n.º 2. Não há falta de conformidade quando o consumidor foi inequivocamente informado, na celebração do contrato, de que uma característica se desviava destes requisitos e aceitou esse desvio separadamente, de forma expressa e inequívoca. A qualificação de uma falta de conformidade necessita de análise concreta.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares, animais, bens vendidos em execução judicial nem imóveis. Identificar o requisito concreto alegadamente não cumprido (incluindo produto diferente do encomendado).',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Existindo falta de conformidade, o consumidor tem os direitos do artigo 15.º. A qualificação exige análise humana.',
 'Fatura ou recibo; confirmação da encomenda; anúncio ou descrição do produto; fotografias; comunicações com o vendedor.',
 'Reconhecimento da falta de conformidade e exercício dos direitos do artigo 15.º.',
 array['defeito', 'produto diferente', 'não corresponde', 'conformidade', 'garantia', 'publicidade']),

('COMPRA_INSTALACAO_INCORRETA_9', 'Compras & Reembolsos', 'Conformidade', 'Falta de conformidade / garantia',
 'Instalação incorreta conta como falta de conformidade',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 9.º',
 'Considera-se existir falta de conformidade sempre que resulte de instalação incorreta, desde que a instalação seja assegurada pelo profissional ou efetuada sob a sua responsabilidade, ou, quando realizada pelo consumidor, a instalação incorreta se deva a deficiências nas instruções de instalação fornecidas pelo profissional.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Identificar quem instalou e que instruções foram fornecidas.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'A instalação incorreta nestas condições é tratada como falta de conformidade do bem.',
 'Fatura com o serviço de instalação; instruções fornecidas; fotografias; relatório técnico.',
 'Reposição da conformidade (reinstalação, reparação ou substituição) nos termos do artigo 15.º.',
 array['instalação', 'mal instalado', 'instruções', 'conformidade']),

('COMPRA_ENTREGA_PRAZO_11', 'Compras & Reembolsos', 'Entrega', 'Entrega',
 'Prazo de entrega e resolução por falta de entrega',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 11.º, n.os 4 a 8 e 11',
 'O profissional deve entregar os bens na data ou dentro do período especificado pelo consumidor, salvo convenção em contrário; na falta de data fixada, deve entregá-los sem demora injustificada e até 30 dias após a celebração do contrato. Não sendo cumprida a entrega, o consumidor tem o direito de pedir a entrega num prazo adicional adequado às circunstâncias e, se os bens não forem entregues nesse prazo, de resolver o contrato. Pode resolver imediatamente, sem prazo adicional, se o profissional se recusar a entregar, se o prazo de entrega for essencial atendendo às circunstâncias da celebração, ou se o consumidor tiver informado o profissional, antes da celebração, de que a entrega em determinado prazo ou data era essencial. Incumbe ao profissional a prova do cumprimento destas obrigações. Saber se o prazo era essencial necessita de análise concreta.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Data do contrato; data ou prazo acordado; data de entrega ou falta dela; pedido de prazo adicional.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'O atraso confere o direito de fixar um prazo adicional e, sem entrega nesse prazo, de resolver o contrato; a resolução imediata só existe nos três casos do n.º 8.',
 'Confirmação da encomenda (data e prazo); comunicações com o vendedor; pedido de prazo adicional; tracking; declaração de resolução.',
 'Entrega dos bens ou resolução do contrato com reembolso.',
 array['encomenda não entregue', 'atraso na entrega', '30 dias', 'prazo adicional', 'resolver contrato']),

('COMPRA_ENTREGA_REEMBOLSO_11', 'Compras & Reembolsos', 'Reembolso', 'Entrega',
 'Reembolso em 14 dias após resolução por falta de entrega',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 11.º, n.os 9 e 10',
 'Após a resolução do contrato por falta de entrega, o profissional deve restituir ao consumidor a totalidade do montante pago até 14 dias após a resolução. Em caso de incumprimento, o consumidor tem direito à devolução em dobro do montante pago, sem prejuízo da indemnização por danos patrimoniais e não patrimoniais a que haja lugar.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Resolução válida nos termos do artigo 11.º; data da resolução; reembolso ou falta dele.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Obrigação de reembolso integral em 14 dias; ultrapassado o prazo, direito à devolução em dobro.',
 'Declaração de resolução e respetiva data; comprovativo do pagamento; extratos bancários.',
 'Reembolso integral ou, passado o prazo, devolução em dobro.',
 array['reembolso', 'encomenda não entregue', '14 dias', 'devolução em dobro']),

('COMPRA_RISCO_TRANSPORTE_11', 'Compras & Reembolsos', 'Entrega', 'Risco durante o transporte',
 'Risco de perda ou dano só passa com a posse física',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 11.º, n.os 1, 12 e 13',
 'O bem considera-se entregue quando o consumidor, ou um terceiro por ele indicado que não o transportador, adquire a posse física do bem. Nos contratos em que o profissional envia os bens, o risco de perda ou dano transfere-se para o consumidor apenas quando este, ou um terceiro por ele indicado que não o transportador, adquire a posse física dos bens. Se o consumidor confiar o transporte a pessoa diferente da proposta pelo profissional, o risco transfere-se com a entrega do bem ao transportador.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Apurar quem escolheu o transportador e se e quando houve posse física.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Se o transporte foi assegurado ou proposto pelo profissional, a perda ou o dano antes da posse física é risco do profissional e a reclamação dirige-se ao vendedor.',
 'Confirmação da encomenda (modalidade de envio); tracking; fotografias da embalagem e do bem; comunicações com o vendedor.',
 'Novo envio, substituição ou reembolso pelo vendedor.',
 array['encomenda perdida', 'transportadora', 'chegou danificado', 'risco', 'posse física']),

('COMPRA_DIREITOS_CONFORMIDADE_15', 'Compras & Reembolsos', 'Conformidade', 'Reparação, substituição, redução e resolução',
 'Direitos perante falta de conformidade e condições de cada um',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigos 15.º e 19.º',
 'Em caso de falta de conformidade, e nas condições da lei, o consumidor tem direito à reposição da conformidade (reparação ou substituição), à redução proporcional do preço ou à resolução do contrato — não pode escolher livremente entre os quatro. Pode escolher entre reparação e substituição, salvo se o meio escolhido for impossível ou impuser ao profissional custos desproporcionados face ao outro; o profissional pode recusar repor a conformidade se ambos forem impossíveis ou desproporcionados. Só pode escolher entre a redução do preço e a resolução se o profissional não tiver reparado ou substituído (ou não o tiver feito nos termos do artigo 18.º), tiver recusado, tiver declarado ou resultar evidente que não o fará em prazo razoável ou sem grave inconveniente, se a falta reaparecer apesar da tentativa, se ocorrer nova falta ou se a gravidade justificar a imediata redução ou resolução. Não há direito à resolução se o profissional provar que a falta de conformidade é mínima. A redução do preço é proporcional à diminuição do valor do bem. Desproporção, prazo razoável, grave inconveniente, gravidade e falta mínima necessitam de análise concreta.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Falta de conformidade dentro do prazo de responsabilidade; histórico dos pedidos ao vendedor e das respostas.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Identifica o direito exercível na fase em que o caso está. Não há livre escolha entre os quatro direitos; os conceitos indeterminados exigem análise humana.',
 'Fatura; prova da falta de conformidade; pedidos ao vendedor e respostas; relatórios ou guias de reparação.',
 'Reparação ou substituição; quando os pressupostos se verifiquem, redução do preço ou resolução com reembolso.',
 array['reparação', 'substituição', 'redução do preço', 'resolução', 'garantia', 'defeito']),

('COMPRA_REJEICAO_30D_16', 'Compras & Reembolsos', 'Conformidade', 'Direito de rejeição (30 dias)',
 'Defeito nos primeiros 30 dias: substituição imediata ou resolução',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 16.º',
 'Nos casos em que a falta de conformidade se manifeste no prazo de 30 dias após a entrega do bem, o consumidor pode solicitar a imediata substituição do bem ou a resolução do contrato. Este direito exige falta de conformidade e não se confunde com a livre resolução dos contratos à distância (que não exige defeito); vale também para compras feitas em loja.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Existe falta de conformidade e manifestou-se até 30 dias após a entrega.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Nesse período o consumidor pode pedir logo a substituição ou a resolução, sem ter de passar primeiro pela reparação. A existência da falta de conformidade exige análise humana.',
 'Data de entrega; data em que o defeito se manifestou e foi comunicado; prova do defeito (fotografias, relatório).',
 'Substituição imediata do bem ou resolução do contrato com reembolso.',
 array['defeito', '30 dias', 'rejeição', 'substituição imediata', 'devolver', 'avariado']),

('COMPRA_REPARACAO_REGRAS_18', 'Compras & Reembolsos', 'Garantia', 'Reparação e substituição',
 'Regras da reparação e da substituição (custos e garantia adicional)',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 18.º, n.os 1 e 4 a 7',
 'Para efeitos de reparação ou substituição, o consumidor disponibiliza os bens a expensas do profissional. Em caso de reparação, o bem reparado beneficia de um prazo de garantia adicional de seis meses por cada reparação, até ao limite de quatro reparações, devendo o profissional transmitir essa informação na entrega do bem reparado. Quando a reparação exigir a remoção de um bem instalado de forma compatível com a sua natureza e finalidade, a remoção e a instalação do bem reparado ou substituto são a expensas do profissional. Havendo substituição, o profissional é responsável pela falta de conformidade do bem sucedâneo nos termos do artigo 12.º e não pode cobrar qualquer custo inerente à normal utilização do bem substituído. Complementa a regra GAR_REPARACAO_30D_18 (gratuitidade, prazo razoável, 30 dias).',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Reparação ou substituição pedida ou realizada.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Custos de envio, remoção, reinstalação ou de utilização normal cobrados ao consumidor podem ser contestados; cada reparação acrescenta seis meses de garantia ao bem reparado, até quatro reparações.',
 'Guias de reparação e datas; faturas de custos cobrados; comunicações com o vendedor.',
 'Devolução de custos indevidos e reconhecimento da garantia adicional.',
 array['reparação', 'garantia adicional', 'seis meses', 'portes', 'substituição', 'custos']),

('COMPRA_RESOLUCAO_REEMBOLSO_20', 'Compras & Reembolsos', 'Reembolso', 'Redução e resolução',
 'Resolução por falta de conformidade e reembolso em 14 dias',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 20.º',
 'O direito de resolução por falta de conformidade exerce-se por declaração ao profissional, designadamente por carta, correio eletrónico ou outro meio suscetível de prova. Se a falta respeitar só a parte dos bens, a resolução pode limitar-se a esses bens, ou abranger os adquiridos em conjunto se não for razoável esperar que o consumidor mantenha só os conformes. O consumidor devolve os bens a expensas do profissional; o profissional reembolsa todos os pagamentos recebidos, incluindo os custos de entrega, no prazo de 14 dias a contar da data em que foi informado da resolução, pelo mesmo meio de pagamento, salvo acordo expresso sem custos para o consumidor, podendo reter o reembolso enquanto os bens não forem devolvidos ou o consumidor não fizer prova do seu envio, salvo quando lhe incumba a recolha. A existência de fundamento para resolver depende do artigo 15.º e necessita de análise concreta.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Fundamento de resolução nos termos do artigo 15.º; data da declaração; devolução ou prova de envio.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Com resolução válida, obrigação de reembolso integral em 14 dias, pelo mesmo meio de pagamento, e devolução a expensas do profissional.',
 'Declaração de resolução; comprovativo de envio ou devolução; comprovativo do pagamento.',
 'Reembolso integral, incluindo custos de entrega.',
 array['reembolso', 'resolução', 'devolver', '14 dias', 'falta de conformidade']),

('COMPRA_BENS_USADOS_12_13', 'Compras & Reembolsos', 'Garantia', 'Bens usados e recondicionados',
 'Prazos nos bens usados e recondicionados',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 12.º, n.º 3; artigo 13.º, n.os 3 e 4',
 'Nos contratos de compra e venda de bens móveis usados, e por acordo entre as partes, o prazo de três anos de responsabilidade do profissional pode ser reduzido a 18 meses, salvo se o bem for anunciado como recondicionado, sendo obrigatória a menção dessa qualidade na fatura, caso em que se aplica o prazo de três anos. Havendo essa redução por acordo, a presunção de que a falta de conformidade existia na entrega aplica-se durante um ano. Decorrido o prazo da presunção, cabe ao consumidor provar que a falta de conformidade existia à data da entrega.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Bem usado ou recondicionado; existência de acordo de redução; menção na fatura.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Sem acordo de redução, ou se o bem foi anunciado como recondicionado, aplica-se o prazo de três anos.',
 'Anúncio; fatura (menção a recondicionado); contrato ou condições com o acordo de redução.',
 'Reconhecimento do prazo de responsabilidade aplicável.',
 array['usado', 'recondicionado', '18 meses', 'garantia', 'segunda mão']),

('COMPRA_COMUNICACAO_PRAZOS_12_17', 'Compras & Reembolsos', 'Garantia', 'Falta de conformidade / garantia',
 'Comunicação da falta de conformidade e prazos para agir',
 'Decreto-Lei n.º 84/2021, de 18 de outubro', 'Artigo 12.º, n.os 4 e 5; artigo 17.º',
 'A comunicação da falta de conformidade deve ser feita, designadamente, por carta, correio eletrónico ou outro meio suscetível de prova. O prazo de responsabilidade do profissional suspende-se desde a comunicação até à reposição da conformidade, devendo o consumidor colocar os bens à disposição do profissional sem demora injustificada. Os direitos do artigo 15.º caducam decorridos dois anos a contar da comunicação da falta de conformidade; este prazo suspende-se enquanto o bem está à disposição do profissional para reparação ou substituição e durante a tentativa de resolução extrajudicial do conflito.',
 'Compra e venda de bem móvel entre consumidor (pessoa singular, para uso não profissional) e profissional (quem vende no âmbito da sua atividade); contrato celebrado a partir de 01/01/2022. Não aplicar a vendas entre particulares. Data da comunicação; períodos em reparação; início de mediação, conciliação ou arbitragem.',
 'https://diariodarepublica.pt/dr/detalhe/decreto-lei/84-2021-172938301', '2022-01-01', null, false, null, null,
 'Permite verificar se o consumidor ainda está em prazo e registar as causas de suspensão.',
 'Comunicação da falta de conformidade com data; guias de reparação; comprovativo de pedido de mediação ou arbitragem.',
 'Exercício dos direitos dentro do prazo legal.',
 array['prazo', 'caducidade', 'comunicar defeito', 'dois anos', 'garantia']),

('COMPRA_LR_BENS_INICIO_10', 'Compras & Reembolsos', 'Livre resolução', 'Livre resolução de contratos à distância',
 'Livre resolução de bens comprados à distância ou fora do estabelecimento',
 'Decreto-Lei n.º 24/2014, de 14 de fevereiro', 'Artigo 10.º, n.º 1, alínea b), e n.os 2 a 4; artigo 11.º, n.os 1 a 3 e 5',
 'Num contrato de compra e venda celebrado à distância ou fora do estabelecimento comercial, o consumidor pode resolver o contrato sem indicar o motivo no prazo de 14 dias ou, nos contratos celebrados no domicílio do consumidor ou durante deslocação organizada pelo fornecedor fora do estabelecimento, de 30 dias, a contar do dia em que o consumidor, ou um terceiro por ele indicado que não o transportador, adquire a posse física dos bens (na encomenda de vários bens entregues separadamente, do último bem; em lotes ou elementos, do último lote ou elemento). Se o fornecedor não prestou a informação pré-contratual sobre o direito de livre resolução, o prazo é de 12 meses a contar do termo do prazo inicial; se a prestar nesse período, o consumidor dispõe de 14 ou 30 dias a partir da receção. O direito exerce-se pelo modelo legal ou por qualquer declaração inequívoca enviada antes do fim do prazo, e incumbe ao consumidor a prova do exercício. As partes podem fixar prazo mais alargado. Não se aplica a compras presenciais no estabelecimento, nem quando haja exceção legal (artigo 17.º).',
 'Só se a compra foi à distância (sem presença física simultânea, por exemplo online, telefone ou catálogo) ou fora do estabelecimento comercial — não usar sem confirmar a forma de contratação, que o formulário não recolhe. Consumidor e fornecedor profissional. Verificar as exceções do artigo 17.º (DIST_EXCECOES_17) e as exclusões do artigo 2.º, n.º 3. Não exige falta de conformidade.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-73222992', null, null, false, null, null,
 'Dentro do prazo, o consumidor pode desistir da compra sem indicar motivo, com as obrigações dos artigos 12.º a 14.º.',
 'Confirmação da encomenda; data de entrega; informação pré-contratual sobre a livre resolução; declaração de resolução e data de envio.',
 'Resolução do contrato e reembolso nos termos do artigo 12.º.',
 array['devolver compra online', '14 dias', 'livre resolução', 'desistir', 'arrependimento', 'compra online']),

('COMPRA_LR_REEMBOLSO_BENS_12', 'Compras & Reembolsos', 'Reembolso', 'Livre resolução de contratos à distância',
 'Livre resolução: retenção do reembolso, custos de entrega e devolução em dobro',
 'Decreto-Lei n.º 24/2014, de 14 de fevereiro', 'Artigo 12.º, n.os 3 a 6',
 'Na livre resolução, o fornecedor não é obrigado a reembolsar os custos adicionais de entrega quando o consumidor solicitou expressamente uma modalidade de entrega diferente e mais onerosa do que a modalidade comummente aceite e menos onerosa proposta. Excetuados os casos em que o fornecedor se oferece para recolher os bens, só é permitida a retenção do reembolso enquanto os bens não forem recebidos ou o consumidor não apresentar prova da devolução. Quando o bem entregue no domicílio num contrato celebrado fora do estabelecimento não puder, pela sua natureza ou dimensão, ser devolvido por correio, cabe ao fornecedor recolhê-lo e suportar o custo. O incumprimento do reembolso no prazo de 14 dias obriga o fornecedor a devolver em dobro, no prazo de 15 dias úteis, os montantes pagos, sem prejuízo de indemnização. Complementa a regra DIST_REEMBOLSO_12.',
 'Livre resolução validamente exercida num contrato à distância ou fora do estabelecimento; data da declaração; data do envio dos bens; reembolso ou falta dele.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-73222992', null, null, false, null, null,
 'A retenção do reembolso para além da prova de devolução e o reembolso fora de prazo podem ser contestados; direito à devolução em dobro em 15 dias úteis.',
 'Declaração de resolução; comprovativo de envio ou devolução; extratos; comunicações.',
 'Reembolso integral ou devolução em dobro.',
 array['reembolso', 'devolução em dobro', 'reter reembolso', 'portes', 'livre resolução']),

('COMPRA_LR_DEVOLUCAO_13_14', 'Compras & Reembolsos', 'Livre resolução', 'Livre resolução de contratos à distância',
 'Livre resolução: devolução do bem, custos e manipulação',
 'Decreto-Lei n.º 24/2014, de 14 de fevereiro', 'Artigos 13.º e 14.º',
 'Na livre resolução, se o fornecedor não se oferecer para recolher o bem, o consumidor deve devolvê-lo no prazo de 14 dias a contar da comunicação da resolução e conservá-lo de modo a poder restituí-lo nas devidas condições de utilização. O custo da devolução é do consumidor, salvo se o fornecedor acordou suportá-lo ou se não informou previamente o consumidor de que tinha de o pagar. O consumidor pode inspecionar o bem com o devido cuidado; só pode ser responsabilizado pela depreciação se a manipulação exceder a habitualmente admitida em estabelecimento comercial, e nunca o é se o fornecedor não o informou do direito de livre resolução. Saber se a manipulação excedeu a habitual necessita de análise concreta.',
 'Livre resolução exercida num contrato à distância ou fora do estabelecimento; data da comunicação e da devolução; informação prévia sobre os custos de devolução e sobre o direito.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-73222992', null, null, false, null, null,
 'Define quem paga a devolução e quando o fornecedor pode imputar a depreciação do bem; a avaliação da manipulação exige análise humana.',
 'Comunicação de resolução; comprovativo de envio e respetivo custo; informação pré-contratual; fotografias do estado do bem.',
 'Devolução nas condições legais sem deduções indevidas.',
 array['devolução', 'portes de devolução', 'produto usado', 'depreciação', 'livre resolução']),

('COMPRA_LOJA_SEM_LR_2', 'Compras & Reembolsos', 'Livre resolução', 'Compra presencial sem defeito',
 'Compra presencial em loja: não há direito legal geral de devolver por mudança de ideias',
 'Decreto-Lei n.º 24/2014, de 14 de fevereiro', 'Artigo 2.º, n.º 1; artigo 3.º (definições de contrato celebrado à distância e fora do estabelecimento)',
 'O regime do Decreto-Lei n.º 24/2014, incluindo o direito de livre resolução, aplica-se apenas aos contratos celebrados à distância e aos contratos celebrados fora do estabelecimento comercial. Numa compra feita presencialmente no estabelecimento do vendedor, este regime não confere ao consumidor um direito geral de devolver um bem sem defeito apenas por ter mudado de ideias. Uma política de trocas ou devoluções da loja é uma condição comercial voluntária: não é um direito legal geral e só pode ser invocada nos termos em que foi efetivamente anunciada ou acordada, o que é um facto a provar no caso.',
 'Compra presencial no estabelecimento comercial do vendedor e bem sem falta de conformidade (havendo defeito, usar as regras do DL 84/2021). Atenção: um contrato celebrado na loja imediatamente depois de o consumidor ter sido contactado pessoal e individualmente fora dela é contrato fora do estabelecimento (artigo 3.º) — confirmar as circunstâncias. Ver também CONS_RETRATACAO_INFO_8 (falta de informação).',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-73222992', null, null, false, null, null,
 'Impede tratar a simples mudança de ideias numa compra em loja como direito legal de livre resolução; a política comercial anunciada é apenas um facto do caso.',
 'Talão ou fatura; política de trocas anunciada (cartaz, talão, site), quando exista; circunstâncias da compra.',
 'Enquadramento correto do pedido: aplicação da política comercial anunciada, se existir, sem a apresentar como direito legal.',
 array['mudei de ideias', 'troca', 'devolução em loja', 'loja física', 'política de devolução']),

-- ===========================================================================
-- GINÁSIOS (setor 'Ginásios') — 7 regras
-- ===========================================================================

('GIN_INFO_CONTRATUAL_8', 'Ginásios', 'Contrato', 'Dever de informação',
 'Dever de informação na adesão ao ginásio',
 'Lei n.º 24/96, de 31 de julho — Lei de Defesa do Consumidor', 'Artigo 8.º, n.º 1, alíneas a), b), c), f), g), h) e l), e n.º 5',
 'O prestador de serviços deve, na negociação e na celebração do contrato, informar o consumidor de forma clara, objetiva e adequada, nomeadamente sobre as características principais do serviço, a sua identidade (nome, endereço e telefone), o preço total, as modalidades de pagamento e de execução, o sistema de tratamento de reclamações e os centros de arbitragem a que adira e a existência de arbitragem necessária, o período de vigência do contrato ou, se for de duração indeterminada ou de renovação automática, as condições de denúncia ou não renovação e as respetivas consequências, incluindo o regime de contrapartidas previstas para a cessação antecipada de contratos com períodos contratuais mínimos, e as consequências do não pagamento. O prestador que viole o dever de informar responde pelos danos que causar ao consumidor. A falta de informação não determina por si só a nulidade de uma cláusula — necessita de análise concreta.',
 'Contrato entre consumidor e entidade que explora uma instalação de fitness. Identificar a informação concreta que faltou ou foi incorreta (por exemplo, período mínimo, renovação automática, encargo de saída) e o momento em que foi prestada.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/lei/1996-34491075', null, null, false, null, null,
 'Fundamenta o pedido de informação e a responsabilidade por danos; não conclui automaticamente pela invalidade de cláusulas.',
 'Contrato; condições gerais; anúncio ou oferta comercial; comprovativo de adesão; comunicações.',
 'Esclarecimento das condições e reparação dos danos causados pela falta de informação.',
 array['ginásio', 'informação', 'período mínimo', 'renovação automática', 'adesão', 'cancelamento']),

('GIN_DIRETOR_TECNICO_4', 'Ginásios', 'Qualidade do serviço', 'Funcionamento e segurança',
 'Diretor técnico e técnicos de exercício físico',
 'Lei n.º 39/2012, de 28 de agosto, na redação vigente', 'Artigos 4.º, 8.º e 16.º',
 'Cada instalação desportiva de fitness deve dispor de pelo menos um diretor técnico, que assume a direção e a responsabilidade pelas atividades desportivas, e de técnicos de exercício físico responsáveis pela orientação e condução do exercício. A identificação do diretor técnico e o seu horário de permanência devem estar afixados em local bem visível para os utentes. O diretor técnico e os técnicos devem atuar diligentemente, assegurando qualidade, segurança, defesa da saúde dos praticantes e respeito pela ética no desporto. A diligência numa situação concreta necessita de análise concreta.',
 'Instalação de fitness abrangida pela Lei n.º 39/2012 (não se aplica, entre outras, a instalações de hotéis reservadas aos hóspedes nem a instalações recreativas sem enquadramento técnico — artigo 2.º). Facto concreto: falta de técnico, falta de afixação, acidente ou orientação inadequada. Não regula o cancelamento do contrato.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2012-155873811', null, null, false, null, null,
 'Permite pedir a identificação do diretor técnico e invocar a falta destes requisitos numa reclamação sobre funcionamento ou segurança.',
 'Fotografias da receção (afixação); descrição do incidente; testemunhas; comunicações com o ginásio.',
 'Cumprimento dos requisitos de enquadramento técnico e resposta ao incidente.',
 array['ginásio', 'diretor técnico', 'personal trainer', 'técnico de exercício', 'segurança']),

('GIN_SEGURO_17', 'Ginásios', 'Qualidade do serviço', 'Funcionamento e segurança',
 'Seguro obrigatório e informação afixada',
 'Lei n.º 39/2012, de 28 de agosto, na redação vigente', 'Artigo 17.º',
 'As instalações desportivas de fitness devem dispor de um seguro nos termos do artigo 14.º do Decreto-Lei n.º 10/2009, de 12 de janeiro, e a informação sobre a existência desse seguro deve estar afixada, em cada instalação, em local visível para os utentes. As coberturas do seguro não estão descritas nesta regra.',
 'Instalação de fitness abrangida pela Lei n.º 39/2012. Acidente ou lesão nas instalações, ou falta da informação afixada.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2012-155873811', null, null, false, null, null,
 'Permite pedir a identificação do seguro e invocar a falta de seguro ou da informação afixada.',
 'Fotografias; relatório do acidente; comunicações com o ginásio.',
 'Identificação do seguro e encaminhamento da participação do acidente.',
 array['ginásio', 'seguro', 'acidente', 'lesão']),

('GIN_REGULAMENTO_INTERNO_19', 'Ginásios', 'Qualidade do serviço', 'Funcionamento e segurança',
 'Regulamento interno obrigatório e afixado',
 'Lei n.º 39/2012, de 28 de agosto, na redação vigente', 'Artigo 19.º',
 'As instalações desportivas de fitness devem dispor de um regulamento interno elaborado pelo proprietário, ou pela entidade que as explore, com as normas de utilização e de segurança a observar pelos utentes, assinado pelo diretor técnico (salvo se emitido pela plataforma eletrónica prevista no Decreto-Lei n.º 102/2017), afixado em local visível na receção e na zona de acesso às áreas de atividade desportiva e instalações de apoio.',
 'Instalação de fitness abrangida pela Lei n.º 39/2012. O ginásio invoca uma regra de utilização ou de segurança; verificar se consta do regulamento interno e se este está afixado. As regras do regulamento interno não substituem as cláusulas do contrato de adesão.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2012-155873811', null, null, false, null, null,
 'Permite pedir o regulamento interno e confrontar a conduta do ginásio com as normas nele previstas.',
 'Regulamento interno (cópia ou fotografia); contrato; comunicações.',
 'Disponibilização do regulamento e cumprimento das normas nele previstas.',
 array['ginásio', 'regulamento interno', 'regras de utilização', 'afixação']),

('GIN_CCG_PRAZO_VIGENCIA_22', 'Ginásios', 'Contrato', 'Cláusulas contratuais gerais',
 'Prazo de vigência ou de denúncia possivelmente excessivo',
 'Decreto-Lei n.º 446/85, de 25 de outubro — Cláusulas Contratuais Gerais', 'Artigos 20.º e 22.º, n.º 1, alínea a)',
 'Nas relações com consumidores são proibidas, consoante o quadro negocial padronizado, as cláusulas contratuais gerais que prevejam prazos excessivos para a vigência do contrato ou para a sua denúncia. Saber se um prazo é excessivo depende do caso: esta regra fundamenta apenas uma possível cláusula abusiva, que necessita de análise concreta; não permite concluir que a cláusula é ilegal.',
 'Contrato de adesão com cláusulas pré-elaboradas; cláusula concreta de período mínimo, duração ou pré-aviso de denúncia identificada.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1985-34436475', null, null, false, null, null,
 'Possível cláusula abusiva — necessita de análise concreta. Não permite concluir automaticamente que a cláusula é ilegal ou nula.',
 'Contrato e condições gerais; cláusula concreta; anúncio da oferta.',
 'Contestação fundamentada da cláusula, se a análise concreta o justificar.',
 array['ginásio', 'período mínimo', 'fidelização', 'pré-aviso', 'cláusula abusiva', 'denúncia']),

('GIN_CCG_CLAUSULA_PENAL_19', 'Ginásios', 'Cancelamento', 'Cláusulas contratuais gerais',
 'Penalização possivelmente desproporcionada',
 'Decreto-Lei n.º 446/85, de 25 de outubro — Cláusulas Contratuais Gerais', 'Artigos 19.º, alínea c), e 20.º',
 'São proibidas, consoante o quadro negocial padronizado, as cláusulas contratuais gerais que consagrem cláusulas penais desproporcionadas aos danos a ressarcir; esta proibição aplica-se nas relações com consumidores. A proporção entre a penalização e os danos depende do caso: esta regra fundamenta apenas uma possível cláusula abusiva, que necessita de análise concreta; não permite concluir que a cláusula é ilegal.',
 'Contrato de adesão com cláusulas pré-elaboradas; cláusula de penalização por cessação antecipada identificada; valor exigido e forma de cálculo.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1985-34436475', null, null, false, null, null,
 'Possível cláusula abusiva — necessita de análise concreta da proporção entre a penalização e os danos. Não permite concluir automaticamente que a cláusula é ilegal ou nula.',
 'Contrato; cláusula de penalização; cálculo do valor exigido; pedido de cancelamento; extratos.',
 'Contestação fundamentada da penalização, se a análise concreta o justificar.',
 array['ginásio', 'penalização', 'cancelar', 'multa', 'cláusula penal', 'cláusula abusiva']),

('GIN_CCG_AUMENTO_PRECO_22', 'Ginásios', 'Alteração contratual', 'Cláusulas contratuais gerais',
 'Aumentos de mensalidade possivelmente abusivos',
 'Decreto-Lei n.º 446/85, de 25 de outubro — Cláusulas Contratuais Gerais', 'Artigo 22.º, n.º 1, alíneas e) e f)',
 'Nas relações com consumidores são proibidas, consoante o quadro negocial padronizado, as cláusulas contratuais gerais que permitam elevações de preços, em contratos de prestações sucessivas, dentro de prazos manifestamente curtos ou, para além desse limite, elevações exageradas, sem prejuízo do artigo 437.º do Código Civil, e as que impeçam a denúncia imediata do contrato quando as elevações dos preços a justifiquem. Saber se um prazo é manifestamente curto ou um aumento exagerado depende do caso: esta regra fundamenta apenas uma possível cláusula abusiva, que necessita de análise concreta; não permite concluir que a cláusula é ilegal.',
 'Contrato de adesão com cláusulas pré-elaboradas; aumento de mensalidade com base numa cláusula do contrato; datas e montantes. Ver também CCG_ALT_UNILATERAL_22.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1985-34436475', null, null, false, null, null,
 'Possível cláusula abusiva — necessita de análise concreta. Não permite concluir automaticamente que a cláusula é ilegal ou nula.',
 'Contrato; cláusula de atualização de preço; comunicação do aumento; mensalidades antes e depois.',
 'Contestação fundamentada do aumento ou saída do contrato, se a análise concreta o justificar.',
 array['ginásio', 'aumento de mensalidade', 'preço', 'cláusula abusiva', 'denúncia']),

-- ===========================================================================
-- GERAIS (setor null) — 2 regras
-- ===========================================================================

('DIST_EXCECOES_17', null, 'Livre resolução', 'Exceções à livre resolução',
 'Exceções ao direito de livre resolução',
 'Decreto-Lei n.º 24/2014, de 14 de fevereiro', 'Artigo 17.º',
 'Salvo acordo das partes em contrário, o consumidor não pode resolver livremente, entre outros, os contratos de: prestação de serviços integralmente prestados após consentimento prévio e expresso do consumidor, que reconheça perder o direito com a execução plena; bens ou serviços cujo preço dependa de flutuações do mercado financeiro; bens confecionados segundo especificações do consumidor ou manifestamente personalizados; bens que por natureza não possam ser reenviados ou se deteriorem ou fiquem rapidamente fora de prazo; bens selados não suscetíveis de devolução por motivos de saúde ou higiene quando abertos após a entrega; bens que fiquem inseparavelmente misturados com outros; gravações áudio ou vídeo ou programas informáticos selados abertos após a entrega; jornais, periódicos ou revistas, exceto assinaturas; hasta pública; alojamento para fins não residenciais, transporte de bens, aluguer de automóveis, restauração ou serviços relacionados com atividades de lazer se o contrato previr uma data ou período de execução específicos; conteúdos digitais sem suporte material cuja execução tenha começado com consentimento e reconhecimento da perda do direito, e confirmação; reparação ou manutenção no domicílio pedida pelo consumidor (havendo direito quanto a serviços ou bens além dos pedidos). A qualificação na exceção necessita de análise concreta quando não for evidente.',
 'Contrato abrangido pelo Decreto-Lei n.º 24/2014 (à distância ou fora do estabelecimento). Identificar a alínea concreta. Ginásios: não decidir automaticamente se uma adesão ou mensalidade contratada online está abrangida pela exceção de serviços relacionados com atividades de lazer com data ou período de execução específicos — análise humana.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2014-73222992', null, null, false, null, null,
 'Impede a aplicação automática da livre resolução quando a exceção se verifica; quando não for evidente, exige análise humana.',
 'Confirmação da encomenda; descrição do bem ou serviço; estado do selo ou da embalagem; consentimento expresso para início do serviço; datas de execução previstas.',
 'Enquadramento correto do pedido de livre resolução.',
 array['exceções', 'livre resolução', 'personalizado', 'selado', 'higiene', 'atividades de lazer']),

('CONS_RETRATACAO_INFO_8', null, 'Livre resolução', 'Falta de informação',
 'Retratação por falta de informação que compromete a utilização',
 'Lei n.º 24/96, de 31 de julho — Lei de Defesa do Consumidor', 'Artigo 8.º, n.º 4',
 'Quando se verifique falta de informação, informação insuficiente, ilegível ou ambígua que comprometa a utilização adequada do bem ou do serviço, o consumidor goza do direito de retratação do contrato relativo à sua aquisição ou prestação, no prazo de sete dias úteis a contar da data de receção do bem ou da data de celebração do contrato de prestação de serviços. Saber se a falta de informação compromete a utilização adequada necessita de análise concreta.',
 'Relação de consumo (consumidor e profissional). Falha de informação concreta e prova de que compromete a utilização adequada; datas de receção ou de celebração. Aplica-se também a compras em loja, mas não substitui a livre resolução nem a garantia.',
 'https://diariodarepublica.pt/dr/legislacao-consolidada/lei/1996-34491075', null, null, false, null, null,
 'Possível direito de retratação no prazo de sete dias úteis; a verificação do pressuposto exige análise humana.',
 'Documentação entregue (instruções, contrato); datas de entrega ou de celebração; comunicação de retratação.',
 'Retratação do contrato quando o pressuposto se confirme.',
 array['retratação', 'falta de informação', 'sete dias úteis', 'instruções', 'informação ambígua'])

on conflict (codigo) do update set
  setor = excluded.setor,
  categoria = excluded.categoria,
  subcategoria = excluded.subcategoria,
  titulo = excluded.titulo,
  diploma = excluded.diploma,
  artigo = excluded.artigo,
  resumo = excluded.resumo,
  condicoes_aplicabilidade = excluded.condicoes_aplicabilidade,
  fonte_url = excluded.fonte_url,
  em_vigor_desde = excluded.em_vigor_desde,
  revogada_em = excluded.revogada_em,
  efeito_juridico = excluded.efeito_juridico,
  provas_necessarias = excluded.provas_necessarias,
  resultado_pretendido = excluded.resultado_pretendido,
  palavras_chave = excluded.palavras_chave,
  ativa = false,
  revista_em = null,
  revista_por = null
-- Nunca reescreve uma regra já revista ou ativa (incluindo as 108 das cargas 1–3).
where public.regras_juridicas.revista_em is null and not public.regras_juridicas.ativa;
